### ISSUE TITLE
Import Econsult Data Page 

### ISSUE THREAD

**Issue by sakshamrai101** [sakshamrai101/Afya_Smart_ML_Project#2]
1. A simple page with an "Import EConcuslt" button to allow importing of econsultation notes in pdf, docx and other text-based formats. 
2. Have a load screen show up while the pdf is importing and then redirect to the next page with three options: "Show Missing Information", "Generate Targeted Questions" and "Display Recommendations".

**Comment by debalina-chowdhury** [comment]
Done by David & Debalina
