### ISSUE TITLE
Services Page - UI Update

### ISSUE THREAD

**Issue by sakshamrai101** [sakshamrai101/Afya_Smart_ML_Project#8]
1. Design the page so that all 3 services are accessible to the PCP (clickable link - indicated by some bright color)
2. Design the page where only 2 out of 3 services are accessible (non-clickable, dim color) 
3. Design the page where only 1 out of the services are accessible.
4. Design the page so that no services are active.

**Comment by debalina-chowdhury** [comment]
Done
